### ISSUE TITLE
Errors and appeal 

### ISSUE THREAD

**Issue by chuksthemodder** [Naseband/SAMP-Peds#1]
Hi sir sorry to disturb please I need the amx file am unable to compile this please

**Comment by Naseband** [comment]
You'll need multiple plugins (as seen in the credits section of the readme or PNEdit.pwn) for this to work. The include versions used when compiling and the plugin versions must match, so you'll need to make sure you have both the plugins and includes installed correctly.

Most of them are really easy to setup, but I can't just send you an AMX for it.

Also, as a side note, I didn't work on this for a long time so I would assume it is a bit out of date. But if you installed all plugins correctly let me know if it still fails to compile.

**Comment by TyAmosMoses** [comment]
Hi, sorry.  I have a problem.  I compiled but the NPCS don't load.
