### ISSUE TITLE
Question sir

### ISSUE THREAD

**Issue by chuksthemodderv** [Naseband/SAMP-Peds#3]
Can this work on lemehost sir, with other actual players. Thanks

**Comment by Naseband** [comment]
I don't know about lemehost specifically. But if you have the ability to run all the required plugins, your server has enough memory for them and you have enough server slots then I see no reason why it wouldn't.

Keep in mind that NPCs in SAMP take player slots. If you have a 32 slot or 64 slot server I would not recommend running it, you'll be left with a very low player count.
